---
title: "Literature data comparison"
date: "`r format(Sys.Date(), '%d %b %Y')`"
number-sections: true
number-offset: 0
toc: true
toc-depth: 2
fig-width: 6
fig-height: 4
df-print: tibble
embed-resources: true
format: 
  html: 
    code-tools: true
    code-fold: show
    code-summary: "Show the code"
    toc-float: true
knitr: 
  opts_chunk: 
    fig.path: "plots/"
    fig.keep: "all"
    dev: ['png', 'pdf']
    dev.args: 
      pdf: 
        encoding: 'WinAnsi'
        useDingbats: false
crossref:
  fig-prefix: Fig.
  tbl-prefix: Table
  ref-hyperlink: true
editor: source
editor_options: 
  chunk_output_type: console
---

# Setup

Using `r R.version.string` , @R, and tidyverse version `r packageVersion("tidyverse")`, @tidyverse.

```{r}
#| label: setup
#| message: false

# load packages
library(tidyverse)

# load scripts
source("scripts/plotting_functions.R")
```

# Data

```{r}

```


```{r}
# load study data
this_data <- 
  readxl::read_excel("output/table1.xlsx", "all") |>
  filter(growth_phase == "stationary") |>
  select("compound", "d13C_avg") |>
  pivot_wider(names_from = "compound", values_from = "d13C_avg") |>
  transmute(
    paper = "this study",
    substrate = "H2/CO2",
    c_substrate_limited = "yes",
    methane = CH4,
    lipids = phytane,
    biomass = biomass
  ) 
this_data |> knitr::kable()

# load literature data
literature_data <- readxl::read_excel("data/clim_figure2_table1.xlsx") |>
  filter(`culture vs field` == "culture") |>
  pivot_wider(
    id_cols = c("paper", "culture vs field", "substrate", "details", "c_substrate_limited"),
    values_from = "d13C_value", names_from = "product"
  )
literature_data |> knitr::kable()

# combine data
data <- bind_rows(this_data, literature_data)
```

# Calculations

```{r}
# calculate fractionation factors
data_calcs <- 
  data |>
  mutate(
    `alpha biomass/methane` = (biomass/1000 + 1) / (methane/1000 + 1),
    `alpha lipids/methane` = (lipids/1000 + 1) / (methane/1000 + 1)
  ) |>
  filter(!if_all(starts_with("alpha"), is.na))
```

# Visualization

```{r}
# theme
my_theme <- theme_bw() +
  theme(
    text = element_text(size = 24),
    axis.text = element_text(size = 20),
    axis.text.x = element_text(hjust = 0.5, vjust = 0.5),
    axis.title.x = element_text(vjust = -1),
    plot.title = element_text(hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(size = .5, linetype = 1),
    legend.position = "right",
    legend.direction = "vertical",
    plot.background = element_blank(), 
    panel.background = element_blank())
```

## Biomass Fractionation

```{r}
#| label: fig-literature-biomass
#| fig-width: 10
#| fig-height: 6
data_calcs |>
  select("paper", "details", "substrate", "c_substrate_limited", "alpha biomass/methane", "culture vs field") |>
  pivot_longer(
    cols = starts_with("alpha"),
    names_to = "factor", values_to = "alpha",
    names_pattern = "alpha (.*)"
  ) |>
  filter(!is.na(alpha)) |>
  ggplot() +
  aes(x = substrate, y = alpha, color = c_substrate_limited, shape = paper) +
  scale_shape_manual(values = c("this study" = 19, "Londry et al., 2008" = 22, "Summons et al., 1998" = 23, "Nguyen et al., 2020" = 24, "Fuchs et al., 1979" = 25)) +
  # data
  geom_hline(yintercept = 1, linetype = 2) + 
  geom_point(size = 4, stroke = 1.5) +
  # facets
  #facet_wrap(factor ~ ., scales = "free_y", switch = "y", ncol = 1) + 
  # scales
 scale_color_manual(values = c("no" = "darkgrey", "yes" = "forestgreen")) +  
  scale_y_continuous(
    name = expression("Fractionation factor (" * epsilon * ")"), labels = function(x) sprintf("%+.0f\U2030", 1000 * (x-1)),
    sec.axis = sec_axis(identity, labels = identity, name = expression("Fractionation factor (" * alpha * ")"))
  ) +
  expand_limits(y = 0.99) +
  # styling
  my_theme +
  theme(
    strip.background = element_blank(),
    strip.placement = "outside",
    panel.spacing = unit(1, "cm"),
    axis.title.y = element_text(margin = margin(r = 12)),       
    axis.title.y.right = element_text(margin = margin(l = 12))
  ) +
  labs(shape = "Data Source", title = "Fractionation of Biomass vs. CH4", color = "Carbon-Limited", x = "Substrate") 
```

## Lipids Fractionation


```{r}
#| label: fig-literature-lipids
#| fig-width: 10
#| fig-height: 6
data_calcs |>
  select("paper", "details", "substrate", "c_substrate_limited", "alpha lipids/methane", "culture vs field") |>
  pivot_longer(
    cols = starts_with("alpha"),
    names_to = "factor", values_to = "alpha",
    names_pattern = "alpha (.*)"
  ) |>
  filter(!is.na(alpha)) |>
  ggplot() +
  aes(x = substrate, y = alpha, color = c_substrate_limited, shape = paper) +
  scale_shape_manual(values = c("this study" = 19, "Londry et al., 2008" = 22, "Summons et al., 1998" = 23, "Nguyen et al., 2020" = 24, "Fuchs et al., 1979" = 25)) +
  # data
  geom_hline(yintercept = 1, linetype = 2) + 
  geom_point(size = 4, stroke = 1.5) +
  # facets
  #facet_wrap(factor ~ ., scales = "free_y", switch = "y", ncol = 1) + 
  # scales
 scale_color_manual(values = c("no" = "darkgrey", "yes" = "forestgreen")) +  
  scale_y_continuous(
    name = expression("Fractionation factor (" * epsilon * ")"), labels = function(x) sprintf("%+.0f\U2030", 1000 * (x-1)),
    sec.axis = sec_axis(identity, labels = identity, name = expression("Fractionation factor (" * alpha * ")"))
  ) +
  expand_limits(y = 0.99) +
  # styling
  my_theme +
  theme(
    strip.background = element_blank(),
    strip.placement = "outside",
    panel.spacing = unit(1, "cm"),
    axis.title.y = element_text(margin = margin(r = 12)),       
    axis.title.y.right = element_text(margin = margin(l = 12))
  ) +
  labs(shape = "Data Source", title = "Fractionation of Lipids vs. CH4", color = "Carbon-Limited", x = "Substrate") 
 # gghighlight(paper == 'this study')
```
